export const SEARCH_REQUESTED = 'SEARCH_REQUESTED';
export const SEARCH_RECEIVED = 'SEARCH_RECEIVED';
export const ARTICLE_CLIPPED = 'ARTICLE_CLIPPED';
export const ARTICLE_UNCLIPPED = 'ARTICLE_UNCLIPPED';
export const CLIPPED_ARTICLE_REQUESTED = 'CLIPPED_ARTICLE_REQUESTED';
export const CLIPPED_ARTICLE_RECEIVED = 'CLIPPED_ARTICLE_RECEIVED';
